import {
  User2,
  Folder,
  Code2,
  Briefcase,
  MessageCircle,
  Settings2,
  Gamepad,
  FileText,
  ShieldAlert,
  Activity,
  Terminal,
  Grid3X3,
  Layers,
} from "lucide-react";

import type { WindowState } from "../types/window";

export const initialWindows: WindowState[] = [
  {
    id: "about",
    title: "About.txt",
    icon: <User2 size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 10,
    position: { x: 120, y: 80 },
    size: { width: 520, height: 420 },
  },

  {
    id: "projects",
    title: "Projects.dir",
    icon: <Folder size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 1,
    position: { x: 160, y: 120 },
    size: { width: 600, height: 450 },
  },

  {
    id: "tech",
    title: "TechStack.exe",
    icon: <Code2 size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 1,
    position: { x: 200, y: 160 },
    size: { width: 450, height: 400 },
  },

  {
    id: "experience",
    title: "Experience.doc",
    icon: <Briefcase size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 1,
    position: { x: 240, y: 200 },
    size: { width: 500, height: 500 },
  },

  {
    id: "contact",
    title: "Contact.exe",
    icon: <MessageCircle size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 1,
    position: { x: 280, y: 240 },
    size: { width: 400, height: 350 },
  },

  // {
  //   id: "terminal",
  //   title: "cmd.exe",
  //   icon: <Terminal size={14} strokeWidth={1.5} />,
  //   isOpen: false,
  //   isMinimized: false,
  //   isMaximized: false,
  //   zIndex: 1,
  //   position: { x: 320, y: 280 },
  //   size: { width: 600, height: 400 },
  // },

  {
    id: "settings",
    title: "Settings.cpl",
    icon: <Settings2 size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 1,
    position: { x: 360, y: 320 },
    size: { width: 500, height: 450 },
  },

  {
    id: "snake",
    title: "Snake.exe",
    icon: <Gamepad size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 1,
    position: { x: 400, y: 360 },
    size: { width: 400, height: 450 },
  },

  {
    id: "tictactoe",
    title: "TicTacToe.exe",
    icon: <Grid3X3 size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 1,
    position: { x: 420, y: 240 },
    size: { width: 420, height: 420 },
  },

  {
    id: "memory",
    title: "MemoryMatch.exe",
    icon: <Layers size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 1,
    position: { x: 460, y: 280 },
    size: { width: 460, height: 420 },
  },

  {
    id: "notes",
    title: "Notes.txt",
    icon: <FileText size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 1,
    position: { x: 440, y: 400 },
    size: { width: 400, height: 400 },
  },

  {
    id: "bughunter",
    title: "BugHunter.exe",
    icon: <ShieldAlert size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 1,
    position: { x: 480, y: 440 },
    size: { width: 800, height: 600 },
  },

  {
    id: "sysmon",
    title: "SysMon.exe",
    icon: <Activity size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 1,
    position: { x: 520, y: 480 },
    size: { width: 500, height: 400 },
  },

  {
    id: "coderunner",
    title: "CodeRunner.exe",
    icon: <Terminal size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 1,
    position: { x: 560, y: 520 },
    size: { width: 500, height: 450 },
  },
];
