import {
  User2,
  Folder,
  Code2,
  Briefcase,
  MessageCircle,
  Settings2,
  Gamepad,
  FileText,
  ShieldAlert,
  Activity,
  Terminal,
  Grid3X3,
  Layers,
} from "lucide-react";

import type { WindowState } from "../types/window";
import userData from "../data/data.json";

export const initialWindows: WindowState[] = [
  {
    id: "about",
    title: userData.system.windows.about,
    icon: <User2 size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 10,
    position: { x: 120, y: 80 },
    size: { width: 520, height: 420 },
  },

  {
    id: "projects",
    title: userData.system.windows.projects,
    icon: <Folder size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 1,
    position: { x: 160, y: 120 },
    size: { width: 600, height: 450 },
  },

  {
    id: "tech",
    title: userData.system.windows.tech,
    icon: <Code2 size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 1,
    position: { x: 200, y: 160 },
    size: { width: 450, height: 400 },
  },

  {
    id: "experience",
    title: userData.system.windows.experience,
    icon: <Briefcase size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 1,
    position: { x: 240, y: 200 },
    size: { width: 500, height: 500 },
  },

  {
    id: "contact",
    title: userData.system.windows.contact,
    icon: <MessageCircle size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 1,
    position: { x: 280, y: 240 },
    size: { width: 400, height: 350 },
  },

  {
    id: "resume",
    title: userData.system.windows.resume,
    icon: <FileText size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 1,
    position: { x: 320, y: 280 },
    size: { width: 700, height: 800 },
  },

  {
    id: "settings",
    title: userData.system.windows.settings,
    icon: <Settings2 size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 1,
    position: { x: 360, y: 320 },
    size: { width: 500, height: 450 },
  },

  {
    id: "snake",
    title: userData.system.windows.snake,
    icon: <Gamepad size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 1,
    position: { x: 400, y: 360 },
    size: { width: 400, height: 450 },
  },

  {
    id: "tictactoe",
    title: userData.system.windows.tictactoe,
    icon: <Grid3X3 size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 1,
    position: { x: 420, y: 240 },
    size: { width: 420, height: 420 },
  },

  {
    id: "memory",
    title: userData.system.windows.memory,
    icon: <Layers size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 1,
    position: { x: 460, y: 280 },
    size: { width: 460, height: 420 },
  },

  {
    id: "notes",
    title: userData.system.windows.notes,
    icon: <FileText size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 1,
    position: { x: 440, y: 400 },
    size: { width: 400, height: 400 },
  },

  {
    id: "bughunter",
    title: userData.system.windows.bughunter,
    icon: <ShieldAlert size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 1,
    position: { x: 480, y: 440 },
    size: { width: 800, height: 600 },
  },

  {
    id: "sysmon",
    title: userData.system.windows.sysmon,
    icon: <Activity size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 1,
    position: { x: 520, y: 480 },
    size: { width: 500, height: 400 },
  },

  {
    id: "coderunner",
    title: userData.system.windows.coderunner,
    icon: <Terminal size={14} strokeWidth={1.5} />,
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 1,
    position: { x: 560, y: 520 },
    size: { width: 500, height: 450 },
  },
];
